# Generated by Django 4.2.6 on 2023-10-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_haven', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
