# Generated by Django 4.2.6 on 2023-10-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_haven', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ['title'], 'verbose_name': 'Dictionary', 'verbose_name_plural': 'Dictionaries'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='estimated_abv',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
