# Generated by Django 4.2.6 on 2023-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_haven', '0005_alter_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'g'), (1, 'kg'), (2, 'piece')], default=0),
        ),
    ]
