# Generated by Django 4.2.6 on 2023-11-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_haven', '0011_guestorder_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='guest_email',
            field=models.EmailField(max_length=254),
        ),
    ]
