# Generated by Django 4.2.6 on 2023-11-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_haven', '0012_alter_guestorder_guest_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userorder',
            options={},
        ),
    ]
